### ISSUE TITLE
Consistency: nestePaginering() vs. nesteForekomst()

### ISSUE THREAD

**Issue by cweber9843** [LtGlahn/nvdbapi-V3#18]
Når `nestePaginering()` er "ferdig", returnerer den `False`, mens `nesteForekomst()` returnerer `None`.
Er det viktig at de har forskjellig oppførsel? 
Ellers hadde jeg foreslått at begge returnerer `False` (eller i hvert fall det samme), slik  at man kan bygge samme logikk rundt.

**Comment by LtGlahn** [comment]
won't fix, dette er fullstendig transparent for brukeren. Nå itererer vi på pythonsk vis, takket være bidrag fra @frafra
