### ISSUE TITLE
dobbelt objekter etter enkelt request

### ISSUE THREAD

**Issue by bojanmilojkovic77** [LtGlahn/nvdbapi-V3#35]
Hei,

Kanskje det er min feil, men med enkelt koden: 
[feil_NVDB_python_github.txt](https://github.com/LtGlahn/nvdbapi-V3/files/9972223/feil_NVDB_python_github.txt)
Jeg fikk dobbelt objekter som resultat av koden.
Det skjer med andre objekttyper også.

**Comment by bojanmilojkovic77** [comment]
Jeg skjøner nå! linje objekter kommer delt på strekninger. Hvis en linje objekt ligger på 3 strekninger det skal bli delt på tre men denne tre sammen skal gi sammen lengde av den objekt!

**Comment by LtGlahn** [comment]
Beklager tregt svar, har vært travelt! Det er helt riktig! Lange objekter kan være delt inn i mange segmenter, iallfall er det standardverdiene med _sokeobjekt.to_records()_
