### ISSUE TITLE
endring i NVDB

### ISSUE THREAD

**Issue by bojanmilojkovic77** [LtGlahn/nvdbapi-V3#36]
Der er endring i NVDB og der kommer ignorert feil:

Fant ingen verdi i denne egenskapen, ignorerer:
 {
    "id": 5218,
    "navn": "Skiltutforming",
    "egenskapstype": "Bin\u00e6r",
    "datatype": "Bin\u00e6rObjekt",
    "blob_format": "C:\\Users\\liszby\\NVDB\\Prosjekter\\FVFG289_20190612\\blob2350_0001.dat\n"
}

**Comment by LtGlahn** [comment]
Egenskaper i NVDB kan være mangelfullt utfylt, ja! Det får du ikke løst via dette biblioteket.
