### ISSUE TITLE
nvdb2geojson is missing

### ISSUE THREAD

**Issue by frafra** [LtGlahn/nvdbapi-V3#37]
`nvdb2geojson` is mentioned by `README.md`, but is not available in the repository. It looks like it has never been added:

```
$ git grep nvdb2geojson
README.md:3. Noen funksjoner _(f.eks. nvdb2geojson)_ tar et slik søkeobjekt og transformerer til andre datastrukturer, tabulære data m.m.
```

**Comment by LtGlahn** [comment]
Here's an example of how to dump NVDB-data to geojson using the pandas + geopandas libraries. I'll add this to the documentation, then close this issue: https://gist.github.com/LtGlahn/5a6993ee4d36e675fa74f5a6d6d61b01
