### ISSUE TITLE
(x, y) inverted in EPSG:4326?

### ISSUE THREAD

**Issue by frafra** [LtGlahn/nvdbapi-V3#38]
I tried this code, but it looks that the coordinates are inverted. It looks like a server issue, actually.

https://github.com/LtGlahn/nvdbapi-V3/blob/4ac0996946ee9b581ff094ed77d04b691021053a/nvdbapiv3/nvdbapiv3.py#L307

**Comment by frafra** [comment]
It has been confirmed that this is a server issue, so the client should invert the coordinate in EPSG:4326.

**Comment by LtGlahn** [comment]
Sorry for the late reply, my notifcation settings were not adequate. The lat, lon versus lon, lat debate is ... cumbersome. There simply is no perfect solutions: Some client software expects lon, lat, other software must flip those into to lat, lon. 

On a more theoretical angle, the good people behind NVDB api asked leading geodetic expert what the epsg:4326 definition actually says, and implemented that.

For anyhone needing help flipping (lat,lon,heigth) => (lon,lat,height), here's a oneliner using shapely that will work for both 3D and 2D coordinates, for any geometric type: https://gist.github.com/LtGlahn/9123ff39858f275360b57764e6379ca6

**Comment by frafra** [comment]
Thank you; I am using that already. I haven't considered that some EPSG code could have lat/lon swapped :) I should look more into that.

The problem is that the server inverts lat/lon when using EPSG:4326. Shouldn't the client or nvdbapi provide a consistent lat/lon?

**Comment by frafra** [comment]
I am sorry, I might have not expressed it correctly. I was just puzzled by the fact that NVDB returns lat/lon using some EPSG codes, while lon/lat using some others.
Thanks again for your support and explanation :)
