### ISSUE TITLE
offset support

### ISSUE THREAD

**Issue by frafra** [LtGlahn/nvdbapi-V3#39]
Hei,
I was trying to implement support for an `offset` parameter. NVDB API supports `start`, which is a unique value in the metadata, but it cannot be computed in advance, so to get the 10th page, I need to fetch the 10 pages before. I can use `inkluder=minum` when I just want to move forward, but it seems not very efficient. I tried to cache the value of `start`, based on the parameter, but I am not sure if it is a great idea, and it adds complexity.

Do you have any suggestion for doing that?

**Comment by LtGlahn** [comment]
Those pages are created dynamically on your initial request, and are NOT persistent nor reusable (though they will be accessible for a limited time). I strongly advise against implementing more logic than just starting at page 1, fetch data and proceed to the next page untill empty. 

There is some wiggle room in this code base, though. If you inspect the attributes of the "søkeobjekt" you will see that it keeps track of the page number. Not sure why, but I probably thought it might come in handy some day. You could play around with "søkeobjekt" - attributes and see what's happening to gain more insight into if that logic is useful or not (which I doubt, but feel free to experiment).
