### ISSUE TITLE
".filter( { 'egenskap' " virker ikke

### ISSUE THREAD

**Issue by bojanmilojkovic77** [LtGlahn/nvdbapi-V3#43]
koden med filter egenskap virker ikke, uten egenskap filter virker bra.
def nvdb_pandas(data_nummer, fylke, vegsystem):#, kontraktt = ""):
    v = nvdb.nvdbFagdata(data_nummer)
    v.filter( { 'fylke' : fylke } )
    v.filter( { 'vegsystemreferanse' : vegsystem } )
    v.filter( { 'egenskap': '5530=11578 OR 5530=8872 OR 5530=8873 OR 5530=8874 OR 5530=8875 OR 5530=8876 OR 5530=8877 OR 5530=8878 OR 5530=8879 OR 5530=11578'} )
    objekt = pd.DataFrame(v.to_records( geometri=True ))
    return(objekt)

feil melding:

Forespørselen ble avvist. Kontakt IT ved behov for bistand. Oppgi support ID 15226926674303222886

The requested URL was rejected. Please consult with your administrator.

Your support ID is: 15226926674303222886

[[Go Back]](javascript:history.back();)

**Comment by LtGlahn** [comment]
Du må bruke paranteser, slik som vi diskuterte på epost.
